{{- if .Values.preSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: odoo-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pre-sync-script
        image: "{{ .Values.preSync.image }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y openssh-client
            echo "Starting Odoo update on the server..."
            
            # Ensure the /root/.ssh directory exists
            mkdir -p /root/.ssh
            
            # Fix permissions for the SSH key
            chmod 600 /root/.ssh/id_rsa
            # Add the host to known_hosts
            ssh-keyscan -H k8s.wesolved.cloud >> /root/.ssh/known_hosts
            
            # Run the update script on the remote server
            ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa root@k8s.wesolved.cloud "sh /etc/wesolved/build/scripts/main-deploy.sh"
            echo "Odoo update complete."
        volumeMounts:
        - name: ssh-keys
          mountPath: /root/.ssh
          readOnly: false
      restartPolicy: OnFailure
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
{{- end }}
