{{- if .Values.preSync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: odoo-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pre-sync-script
        image: "{{ .Values.preSync.image }}"
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y openssh-client
            echo "Starting Odoo update on the server..."
            
            # Ensure /root/.ssh directory exists
            mkdir -p /root/.ssh

            # Debugging: Check where the symlinks point to
            echo "id_rsa points to:"
            ls -l /root/.ssh/id_rsa
            echo "known_hosts points to:"
            ls -l /root/.ssh/known_hosts

            # Directly fix permissions for the actual files in the '..data' directory
            chmod 600 /root/.ssh/../data/id_rsa
            chmod 600 /root/.ssh/../data/known_hosts

            # Check permissions after applying changes
            echo "Permissions after change:"
            ls -l /root/.ssh/../data/id_rsa
            ls -l /root/.ssh/../data/known_hosts

            # Add the host to known_hosts, directly modifying the actual file
            ssh-keyscan -H k8s.wesolved.cloud >> /root/.ssh/../data/known_hosts

            # Debugging: Verify the known_hosts file contents
            cat /root/.ssh/../data/known_hosts

            # Run the update script on the remote server
            ssh -o StrictHostKeyChecking=no -i /root/.ssh/../data/id_rsa root@k8s.wesolved.cloud "sh /etc/wesolved/build/scripts/main-deploy.sh"
            echo "Odoo update complete."
        volumeMounts:
        - name: ssh-keys
          mountPath: /root/.ssh
          readOnly: false
      restartPolicy: OnFailure
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
{{- end }}
